choco install -y `
    7zip `
    autohotkey `
    discord `
    dropbox `
    epicgameslauncher `
    firefox `
    foxitreader `
    git `
    googlechrome `
    googledrive `
    hwinfo `
    jbs `
    keepass `
    microsoft-teams `
    nordvpn `
    notepadplusplus `
    onedrive `
    paint.net `
    parsec `
    powertoys `
    pycharm-community `
    python `
    qbittorrent `
    rainmeter `
    razer-synapse-3 `
    spotify `
    steam `
    streamdeck `
    vlc `
    vscode `
    whatsapp `
    wireguard `
    wiztree
